/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shopping;

import java.util.ArrayList;

/**
 *
 * @author phamon
 */
public class IndividualsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form IndividualsJFrame
     */
    public IndividualsJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        IndividualDetailsjTextArea = new javax.swing.JTextArea();
        TitlejLabel = new javax.swing.JLabel();
        RemoveIndividualjComboBox = new javax.swing.JComboBox();
        RemoveIndividualjButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        AddNewjLabel = new javax.swing.JLabel();
        nameJTextField = new javax.swing.JTextField();
        AddNamejLabel = new javax.swing.JLabel();
        AddVegetarianjCheckBox = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        peanutsjCheckBox = new javax.swing.JCheckBox();
        nutsjCheckBox = new javax.swing.JCheckBox();
        eggsjCheckBox = new javax.swing.JCheckBox();
        milkjCheckBox = new javax.swing.JCheckBox();
        fishjCheckBox = new javax.swing.JCheckBox();
        shellfishjCheckBox = new javax.swing.JCheckBox();
        soyjCheckBox = new javax.swing.JCheckBox();
        wheatjCheckBox = new javax.swing.JCheckBox();
        AddIndividualjButton = new javax.swing.JButton();
        ClearAddjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IndividualDetailsjTextArea.setEditable(false);
        IndividualDetailsjTextArea.setColumns(20);
        IndividualDetailsjTextArea.setRows(5);
        aL.add(new Individual("Adam", false));
        aL.add(new Individual("John", true));
        aL.add(new Individual("Paul", false));
        aL.add(new Individual("Tony", false));
        String s = null;
        for (int x = 0; x<aL.size(); x++) {

            s = s + aL.get(x).toString(1)+ "\n\n";
        }
        IndividualDetailsjTextArea.setText(s);
        jScrollPane1.setViewportView(IndividualDetailsjTextArea);

        TitlejLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TitlejLabel.setText("Family Members");

        RemoveIndividualjComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        RemoveIndividualjButton.setText(" Remove Individual ");

        AddNewjLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        AddNewjLabel.setText("Add New Individual");

        nameJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameJTextFieldActionPerformed(evt);
            }
        });

        AddNamejLabel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddNamejLabel.setText("Name");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Vegetarian");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Allergies:");

        peanutsjCheckBox.setText("Peanuts");
        peanutsjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                peanutsjCheckBoxActionPerformed(evt);
            }
        });

        nutsjCheckBox.setText("Other Nuts");

        eggsjCheckBox.setText("Eggs");

        milkjCheckBox.setText("Milk");

        fishjCheckBox.setText("Fish");

        shellfishjCheckBox.setText("Shellfish");

        soyjCheckBox.setText("Soy");

        wheatjCheckBox.setText("Wheat");
        wheatjCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wheatjCheckBoxActionPerformed(evt);
            }
        });

        AddIndividualjButton.setText("Add");
        AddIndividualjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddIndividualjButtonActionPerformed(evt);
            }
        });

        ClearAddjButton.setText("Clear");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitlejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddNewjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(ClearAddjButton)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(AddIndividualjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(AddNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(AddVegetarianjCheckBox)
                                        .addComponent(nutsjCheckBox)
                                        .addComponent(milkjCheckBox)
                                        .addComponent(shellfishjCheckBox)
                                        .addComponent(wheatjCheckBox))))
                            .addComponent(peanutsjCheckBox)
                            .addComponent(eggsjCheckBox)
                            .addComponent(fishjCheckBox)
                            .addComponent(soyjCheckBox))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(RemoveIndividualjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(54, 54, 54)
                                .addComponent(RemoveIndividualjButton))
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(AddNewjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TitlejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(AddNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(nameJTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(AddVegetarianjCheckBox)
                                .addGap(59, 59, 59)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(peanutsjCheckBox)
                            .addComponent(nutsjCheckBox))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eggsjCheckBox)
                            .addComponent(milkjCheckBox))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fishjCheckBox)
                            .addComponent(shellfishjCheckBox))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(soyjCheckBox)
                            .addComponent(wheatjCheckBox))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddIndividualjButton)
                            .addComponent(ClearAddjButton))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RemoveIndividualjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveIndividualjButton))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void peanutsjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_peanutsjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_peanutsjCheckBoxActionPerformed

    private void wheatjCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wheatjCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_wheatjCheckBoxActionPerformed

    private void nameJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameJTextFieldActionPerformed

    private void AddIndividualjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddIndividualjButtonActionPerformed
        // TODO add your handling code here:
        
        if (nameJTextField != null) {
            
            Individual temp = new Individual(nameJTextField.getText(), AddVegetarianjCheckBox.isSelected());
            Admin.displayIndividual(temp);
        }
    }//GEN-LAST:event_AddIndividualjButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void createJFrame() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualsJFrame().setVisible(true);
            }
        });
    }
    
    
    private ArrayList <Individual> aL = new ArrayList(); 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddIndividualjButton;
    private javax.swing.JLabel AddNamejLabel;
    private javax.swing.JLabel AddNewjLabel;
    private javax.swing.JCheckBox AddVegetarianjCheckBox;
    private javax.swing.JButton ClearAddjButton;
    private javax.swing.JTextArea IndividualDetailsjTextArea;
    private javax.swing.JButton RemoveIndividualjButton;
    private javax.swing.JComboBox RemoveIndividualjComboBox;
    private javax.swing.JLabel TitlejLabel;
    private javax.swing.JCheckBox eggsjCheckBox;
    private javax.swing.JCheckBox fishjCheckBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JCheckBox milkjCheckBox;
    private javax.swing.JTextField nameJTextField;
    private javax.swing.JCheckBox nutsjCheckBox;
    private javax.swing.JCheckBox peanutsjCheckBox;
    private javax.swing.JCheckBox shellfishjCheckBox;
    private javax.swing.JCheckBox soyjCheckBox;
    private javax.swing.JCheckBox wheatjCheckBox;
    // End of variables declaration//GEN-END:variables
}
