/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package shopping;

import java.util.ArrayList;

/**
 *
 * @author phamon
 */
public class OneRecipeDisplayJFrame extends javax.swing.JFrame {

    /**
     * Creates new form OneRecipeDisplayJFrame
     */
    public OneRecipeDisplayJFrame(String recipeName, ArrayList recipeDesc) {
        
        this.recipeName = recipeName;
        this.recipeDesc = recipeDesc;
        initComponents();
    }
    
//    public OneRecipeDisplayJFrame() {
//        initComponents();
//    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RecipeNamejLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        RecipeProcedurejTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        RecipeNamejLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        RecipeNamejLabel.setText(recipeName);

        RecipeProcedurejTextArea.setEditable(false);
        RecipeProcedurejTextArea.setColumns(20);
        RecipeProcedurejTextArea.setLineWrap(true);
        RecipeProcedurejTextArea.setRows(5);
        RecipeProcedurejTextArea.setWrapStyleWord(true);
        String s = "";
        for (int x = 0; x<recipeDesc.size();x++) {

            s = s + recipeDesc.get(x) + "\n \n";

        }

        RecipeProcedurejTextArea.setText(s);
        jScrollPane1.setViewportView(RecipeProcedurejTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
                    .addComponent(RecipeNamejLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RecipeNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public void CreateJFrame(final String recipeName, final ArrayList recipeDesc) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneRecipeDisplayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneRecipeDisplayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneRecipeDisplayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneRecipeDisplayJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneRecipeDisplayJFrame(recipeName, recipeDesc).setVisible(true);
                
            }
        });
    }
    
    private String recipeName;
    private ArrayList <String> recipeDesc;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RecipeNamejLabel;
    private javax.swing.JTextArea RecipeProcedurejTextArea;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
